#
# webapptest file, generated by webapptest-create on 2018/03/12-22:08:05
#
# EDITING REQUIRED BEFORE THIS RUNS. Must-change values are marked with ???
#

use strict;
use warnings;

# package ???;

use UBOS::WebAppTest;

my $TEST = UBOS::WebAppTest->new(
    appToTest   => '???',
    accessoriesToTest => [
            '???',
            '???',
            '???'
    ],
    description => '???',
    checks      => [
            UBOS::WebAppTest::StateCheck->new(
                    name  => '???',
                    check => sub {
            # UBOS::WebAppTest::StateTransition->new(
            #         name  => '???',
            #         transition => sub {

                        my $c = shift;
                        $c->getMustRedirect( '', '/?title=/srv/http/sites/s48f12055ae06cfa693b792761e9dd4536b24941b/wiki', 301, 'Not redirecting correctly' );
                        return 1;
                    }
            )
    ]
);

$TEST;
